worker_processes auto;
pid /run/nginx.pid;

events { worker_connections 1024; }

http {
    sendfile on;
    tcp_nopush on;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    upstream django {
        server backend:8000;
    }

    server {
        listen 80;
        server_name _;

        location /static/ {
            alias /vol/static/;
        }

        location /media/ {
            alias /vol/media/;
        }

        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass http://django;
        }
    }
}
